### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by toteph42** [contao/skeleton-bundle#2]
Please fix (README)

`vendor/bin/php-cs-fixer fix -v`
`vendor/bin/phpunit`

They do not exist

**Comment by leofeyer** [comment]
You need to run `composer update` before you can run the CS fixer and the unit tests.

**Comment by toteph42** [comment]
I:\www\contao>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
**Nothing to install or update**
Generating autoload files
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class

 Added/updated the web/app.php file.
 Added/updated the web/app_dev.php file.
...
`
Director output:
I:\www\contao>dir vendor\bin /b
contao-console
contao-console.bat
doctrine
doctrine-dbal
doctrine-dbal.bat
doctrine.bat
lessc
lessc.bat
minifycss
minifycss.bat
minifyjs
minifyjs.bat
pscss
pscss.bat
security-checker
security-checker.bat
uaparser
uaparser.bat
update-psl-icann-section
update-psl-icann-section.bat
var-dump-server
var-dump-server.bat

**REQUEST IS VALID!!!**

**Comment by leofeyer** [comment]
Can you please also post the output of `dir vendor /b`?

**Comment by syncgw** [comment]
I:\www\contao>dir vendor\bin /b
contao-console
contao-console.bat
doctrine
doctrine-dbal
doctrine-dbal.bat
doctrine.bat
lessc
lessc.bat
minifycss
minifycss.bat
minifyjs
minifyjs.bat
pscss
pscss.bat
security-checker
security-checker.bat
uaparser
uaparser.bat
update-psl-icann-section
update-psl-icann-section.bat
var-dump-server
var-dump-server.bat

**Comment by toteph42** [comment]
I:\www\contao>dir vendor /b
ausi
autoload.php
bacon
beberlei
bin
clue
codefog
composer
con4gis
contao
contao-community-alliance
contao-components
dasprid
doctrine
egulias
friendsofsymfony
guzzlehttp
imagine
isotope
jdorn
knplabs
lcobucci
leafo
league
lexik
matthiasmullie
menatwork
michelf
monolog
nelmio
ocramius
oyejorge
paragonie
patchwork
php-http
phpspec
phpunit
psr
scheb
sensio
sensiolabs
simplepie
sonata-project
spomky-labs
swiftmailer
symfony
tecnickcom
terminal42
toflar
true
twig
ua-parser
webmozart
zendframework

**Comment by leofeyer** [comment]
Did you edit the `composer.json` file? Because there are vendor folders missing (see https://github.com/contao/skeleton-bundle/blob/master/composer.json#L21-L30).

**Comment by toteph42** [comment]
Installation:
composer create-project --no-dev contao/managed-edition .
composer require terminal42/contao-changelanguage
composer require terminal42/contao-autoregistration
composer require isotope/isotope-core
composer require con4gis/forum 
composer require codefog/contao-cookiebar

composer update - same # of files in vendor/bin

Then I followed instructions provided at https://gist.github.com/joergmoldenhauer/90fa0c9c6af2c7a36bdbc2d039095142 (install "Hello world" bundle; here I added my new bundle to composor.json)

composer update - still same # of files in vendor/bin (of course my bundle was added)

**Comment by leofeyer** [comment]
If you add the `--no-dev` flag, of course the dev requirements are not installed.

**Comment by toteph42** [comment]
You're right. I picked up that from somewhere. Please apologize.
